<?php

namespace Plastonick\Euros;

class Flag
{
    public static function from(string $tla): string
    {
        return match ($tla) {
            'ALB' => '🇦🇱',
            'ALG' => '🇩🇿',
            'ARG' => '🇦🇷',
            'AUS' => '🇦🇺',
            'AUT' => '🇦🇹',
            'BEL' => '🇧🇪',
            'BIH' => '🇧🇦',
            'BRA' => '🇧🇷',
            'CAN' => '🇨🇦',
            'CIV' => '🇨🇮',
            'CMR' => '🇨🇲',
            'COD' => '🇨🇩',
            'COL' => '🇨🇴',
            'CPV' => '🇨🇻',
            'CRC' => '🇨🇷',
            'CRO' => '🇭🇷',
            'CUW' => '🇨🇼',
            'CZE' => '🇨🇿',
            'DEN' => '🇩🇰',
            'ECU' => '🇪🇨',
            'EGY' => '🇪🇬',
            'ENG' => '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
            'ESP' => '🇪🇸',
            'FIN' => '🇫🇮',
            'FRA' => '🇫🇷',
            'GEO' => '🇬🇪',
            'GER' => '🇩🇪',
            'GHA' => '🇬🇭',
            'HAI' => '🇭🇹',
            'HUN' => '🇭🇺',
            'IRN' => '🇮🇷',
            'IRQ' => '🇮🇶',
            'ITA' => '🇮🇹',
            'JOR' => '🇯🇴',
            'JPN' => '🇯🇵',
            'KOR' => '🇰🇷',
            'KSA' => '🇸🇦',
            'MAR' => '🇲🇦',
            'MEX' => '🇲🇽',
            'NED' => '🇳🇱',
            'NOR' => '🇳🇴',
            'NZL' => '🇳🇿',
            'PAN' => '🇵🇦',
            'PAR' => '🇵🇾',
            'POL' => '🇵🇱',
            'POR' => '🇵🇹',
            'QAT' => '🇶🇦',
            'ROU' => '🇷🇴',
            'RSA' => '🇿🇦',
            'RUS' => '🇷🇺',
            'SCO' => '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
            'SEN' => '🇸🇳',
            'SRB' => '🇷🇸',
            'SUI' => '🇨🇭',
            'SVK' => '🇸🇰',
            'SVN' => '🇸🇮',
            'SWE' => '🇸🇪',
            'TUN' => '🇹🇳',
            'TUR' => '🇹🇷',
            'UKR' => '🇺🇦',
            'URY' => '🇺🇾',
            'USA' => '🇺🇸',
            'UZB' => '🇺🇿',
            'WAL' => '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
        };
    }
}
